### ISSUE TITLE
BluetoothLE BackgroundTask, same problem at new build(10512)

### ISSUE THREAD

**Issue by RuslanSCH** [Microsoft/Windows-universal-samples#127] opened 2015-08-13 11:00 UTC
Hello,

I have same problem at new build:

{"Access is denied.\r\n\r\nYour App does not have permission to use Bluetooth in the background. Make sure you have declared the Task Type 'bluetooth' in your manifest."}

It war use on Lumia 640DS.
Kiran Pathakota and Lisa Ong wrote, that this issue will be fixed at 10240 build.
What should we doing now?

**Comment by Pawel2420** [comment] 2015-08-13 12:44
Hi,
I can confirm the same issue with Lumia 435 Windows 10 Mobile 10.10512.1000 The sample https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BluetoothAdvertisement in Scenario 3 & 4. The error message is:
"WinRT information: Your App does not have permission to use Bluetooth in the background. Make sure you have declared the Task Type 'bluetooth' in your manifest."

I have checked and the Task Type 'bluetooth' in manifest is declared. Do you know where is the problem?

**Comment by kpathakota** [comment] 2015-08-13 18:15
Hello, does this happen when you press the run button in scenarios 3/4?

**Comment by Pawel2420** [comment] 2015-08-13 18:47
Yes.
Scenarios 1 and 2 are working properly.

**Comment by kpathakota** [comment] 2015-08-14 01:31
I just loaded up a phone with that build but I'm unable to repro it.  Can you go to Settings -> Privacy -> Background Apps and make sure that Bluetooth Advertisement C# Sample can run in the background?

**Comment by Pawel2420** [comment] 2015-08-14 06:39
I checked. This option is enabled.

**Comment by RuslanSCH** [comment] 2015-08-14 08:10
Yes, it's happen only in background scenarios. And option for backgroundtask is enabled

**Comment by kpathakota** [comment] 2015-08-14 18:04
Do other Background samples work?  Could you try the  BackgroundTask sample and let me know if that works properly?

**Comment by Pawel2420** [comment] 2015-08-14 19:23
I checked. Scenarios 1..5 are working properly.

**Comment by RuslanSCH** [comment] 2015-08-17 12:33
Hey Pawel2420,

can u deploy any app on your Device (Lumia 435 Windows 10 Mobile 10.10512.1000)?
I have troubles with Deployment since this morning

**Comment by Pawel2420** [comment] 2015-08-18 07:21
Yes I can.

**Comment by RuslanSCH** [comment] 2015-08-18 07:30
Thank you,

after re-install VS i can it too...

**Comment by AdamBraden** [comment] 2015-08-18 18:45
Closing as issues appear to have been resolved

**Comment by RuslanSCH** [comment] 2015-08-18 19:30
@AdamBraden  Hey Adam, why are u closing this issue? 

I still cant  use BackroundTask's for BluetoothAdvertisement.... Problem is the same!

**Comment by AdamBraden** [comment] 2015-08-18 20:01
Apologies, I mis-interpreted your earlier response - it looked like your deployment issue was resolved.  I will reopen so the feature team can continue the investigation.

**Comment by RuslanSCH** [comment] 2015-08-18 20:04
@AdamBraden  Thank you!

**Comment by tendimsol** [comment] 2015-08-26 10:35
We have the same problem. Kind of a deal breaker also as we are building a heavy BLE background task dependent application whose development has ground to a halt. Please help. Bump...

**Comment by tendimsol** [comment] 2015-08-26 11:21
http://www.iotnexus.io/wp-content/uploads/2015/04/wp_ss_20150826_0002.png
http://www.iotnexus.io/wp-content/uploads/2015/04/wp_ss_20150826_0003.png
http://www.iotnexus.io/wp-content/uploads/2015/04/screenshot_Wed_Aug_26_13.34.06.png
http://www.iotnexus.io/wp-content/uploads/2015/04/screenshot_Wed_Aug_26_13.34.26.png

**Comment by ankitvijay** [comment] 2015-09-08 10:22
Facing the same issue on Lumia 630, build 10.0.10512.1000. Anyone found out the resolution/ workaround?

**Comment by RuslanSCH** [comment] 2015-09-08 15:42
@ankitvijay Hey, I heard nothing for a few weeks. The problem is a same and we must make a application based on onlineWatcher... I hope the Microsoft Team will fix it!

Next problem, BLEReceivedEventArgs returns the manufacturerSectionsList and its Count always 1 Beacon (advertisement), same Advertisement can block AppLogic for some time ( we must always wait when Watcher receive next Advertisement and its depends on current signalPower of all BLESenders in current area...)

**Comment by walteriousnut** [comment] 2015-10-17 05:14
Any news on this issue? I am on build 10.0.10536.1004 and it is still a problem. Nokia Lumia 930.

**Comment by tendimsol** [comment] 2015-10-17 05:20
This problem turns out to be changes by Microsoft to rules surrounding 'network lifecycle' of Bluetooth functions.

For example - if you try to use the background process in a foreground context. The error has nothing to do with Bluetooth actually being denied. Or any reference to the app package manifest. It is when the actual function is called that it is 'evaluated' for adherence to 'unknown' and 'unspecified' network lifecycle rule conditions. If it fails - you will get this message. Since our code worked, and then stopped - we can only assume that this is the case based on 'changing' network lifecycle code evaluation by Microsoft as they release new builds.

**Comment by virtualswp** [comment] 2015-11-05 03:37
I'm on 10.0.10536.1004 on a Lumia 635 and having similar issues.  I'm also deploying this to IOT Core on the preview build and having similar issues.  Does anyone know what the official status is?  Is this an issue on the Windows Universal Platform Samples or Windows Mobile 10.0.10536.1004 / Windows IOT Core current build?

Thanks

**Comment by virtualswp** [comment] 2015-11-06 02:23
Just downloaded Windows 10 Mobile v 10.0.10581.0 and the issue still exists unfortunately.

**Comment by oldnewthing** [comment] 2016-04-14 18:12
Latest comment in the thread says that the issue has been resolved.

**Closed by oldnewthing** 2016-04-14 18:12 UTC
