### ISSUE TITLE
XamlCommanding sample - Scenario8 - DynamicCommandBar - forever in MeasureOverride method

### ISSUE THREAD

**Issue by Klepeto** [Microsoft/Windows-universal-samples#779] opened 2017-11-05 20:41 UTC
When I run Scenario 8 in XamlCommanding sample (C#), app freezes. It calls the `MeasureOverride `method over and over.

**Comment by oldnewthing** [comment] 2017-11-05 21:59
Duplicate of issue #250.

**Closed by oldnewthing** 2017-11-05 21:59 UTC
Labels: xaml

**Comment by cwey** [comment] 2019-05-09 12:24
Any progress on this? I am running into the same issue.
