### ISSUE TITLE
SystemMediaTransportControls works on desktop build 14393 but not phone build 14393

### ISSUE THREAD

**Issue by zipponator** [Microsoft/Windows-universal-samples#496] opened 2016-10-02 15:22 UTC
Hi!
I can't seem to get the SystemMediaTransportControls sample to work on phone. If I run it on desktop (x86, Debug or Release), it works fine. When I press Volume up when playing a file, I get the media controls like I should.

But on phone (ARM, Debug or Release, debugging over USB or running stand-alone on the phone) I get the "standard" volume "Media + Apps" slider, and no media transport controls ...

Note: I do get the pause, back, next media controls on the lock screen (overlayed on the lock screen). But not when i press volume up/down. And when i press up/down volume on the lock screen, that still shows the regular "Media + apps" slider, not the extended one with media controls.

I've tried to apply the workaround for issue #376 (by setting IsEnabled = true; at the beginning of Scenarrio1.SetupSystemMediaTransportControls, and then setting it to false at the end of that function) but that doesn't help either.

OS builds on both desktop and phone are 10.0.14393. (10.0.14393.189 on the phone, to be exact). The phone is a Lumia 950.

**Comment by aarononeal** [comment] 2016-10-02 17:46
Thank you for the report. I believe there is an OS issue and I'm following up with the team to find out where we are with servicing.

**Comment by aarononeal** [comment] 2016-10-03 20:31
Can you tell me, were you playing an audio file or a video file?

**Comment by aarononeal** [comment] 2016-10-03 20:37
I'm going to assume video for now and close this out as "by design". If audio, I'll re-open. 

Phone shell doesn't display SMTC for video. This is due to legacy where videos on Phone used to be fullscreen only, and the shell hasn't been updated now that this is no longer true. Shell may change this behavior in the future, but for now, this is expected.

**Closed by aarononeal** 2016-10-03 20:37 UTC
Labels: media

**Comment by zipponator** [comment] 2016-10-03 20:40
You're quite right! I tested with two video files yesterday, but now I tried an audio file and then it worked as expected. Thanks!

**Comment by linhnd** [comment] 2017-04-20 18:46
Here's magic: 
Change *MediaPlaybackType* to *MediaPlaybackType.Music*. It will display the UI controls in mobile
Tested: Lumia 950XL, OS 15063
