### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by superbderrick** [Microsoft/Windows-universal-samples#145] opened 2015-08-25 04:25 UTC
When I try to use Uwp app samples  It occured build error like log 
 

Error	CS0012	The type 'IAsyncOperationWithProgress<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.	AdaptiveStreaming	E:\samplecode\Windows-universal-samples-master\Windows-universal-samples-master\Samples\AdaptiveStreaming\cs\Scenario2.xaml.cs	

I just installed visualstudio 2015 enterprise 2015 trial version 14.0.23107.0 D14REL
with latest windows 10 sdk,

When I see   visualstudio 's  References window  
It can see   added Universal Windows References collectly, But I don't know why it occurd build failuer 

How Can I fix?

**Comment by Padanian** [comment] 2015-08-25 06:53
Works for me.

**Comment by superbderrick** [comment] 2015-08-25 07:03
What do you use visualstudio version?

**Comment by Padanian** [comment] 2015-08-25 09:13
same as yours

**Comment by superbderrick** [comment] 2015-08-25 11:30
Is there any way to fix?

**Comment by Padanian** [comment] 2015-08-25 13:28
Try to fork the repo again, and set the folder security permission for user SYSTEM to full rights.

**Comment by oldnewthing** [comment] 2015-10-16 18:06
I've found that doing a "clean" and then rebuilding will sometimes clear this up. My guess is that something went wrong with the original NuGet fetch.

**Comment by superbderrick** [comment] 2015-10-18 02:12
ok perfect

**Comment by Tetramorium** [comment] 2015-12-20 14:34
I have the same issue but with another project. Cleaning and rebuilding does not work for me sadly...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.	WebServerTask	C:\Users\JM\Downloads\samples-develop\samples-develop\App2App WebServer\WebServerApp\WebServerTask\BackgroundTask.cs	59	Active

**Comment by weihsiang-lin** [comment] 2015-12-24 07:08
I have the same error as the above. Anyone can help to comment? Thanks.

**Comment by superbderrick** [comment] 2015-12-24 08:16
In my case I did format my computer :(

**Comment by oldnewthing** [comment] 2016-02-04 00:59
Looks like a duplicate of https://github.com/Microsoft/Windows-universal-samples/issues/195

**Closed by oldnewthing** 2016-02-04 00:59 UTC

**Comment by wearmeout** [comment] 2016-02-27 16:22
same error :(

**Comment by oldnewthing** [comment] 2016-02-27 17:40
Some of the older samples reference the 10240 SDK rather than the 10586 SDK. Update the references to 10586, or install the 10240 SDK.

**Comment by kareemsulthan07** [comment] 2017-09-06 05:31
adding a reference to windows.winmd file located at C:\Program Files (x86)\windows kits\10\UnionMetadata\10.0.15063.0\Facade\ solved the problem for me.

**Comment by chinyavadav** [comment] 2018-05-14 07:01
DOWNLOAD THE VISUAL STUDIO INSTALLTION EXECUTABLE AND MODIFY THE BUILD
(https://codedocu.com/Details?d=1587&a=9&f=181&l=0&v=d&t=UWP-error:-CS0012-You-must-add-a-refernece-to-assembly-Windows)
check that link it worked for me

**Comment by apathub** [comment] 2018-05-29 20:47
> 

adding a reference to windows.winmd file located at C:\Program Files (x86)\windows kits\10\UnionMetadata\10.0.15063.0\Facade\ solved the problem for me.
--

Actually that resolved the error (CS0012) for me.
Just because I am new to C # programming, could somebody explain why in some computer it is required to add the reference and in other it can compile without it.
Notice that the Visual studio configuration and the SDKs are identical in both computers.
Thanks a lot!
