### ISSUE TITLE
Background Audio stops playing after opening the app a second time

### ISSUE THREAD

**Issue by Toolenaar** [Microsoft/Windows-universal-samples#141] opened 2015-08-21 21:05 UTC
I have used your example to create a background audio player for my app. When debugging everything went fine. But now I have published it to the store, and the music playback is muted when starting the app for the second time. 

The first time you play music in the app all works fine, but when I close the app and reopen it, the music playback is muted, it is running because I do see my progress indicator running, there just isn't any sound. The sound comes back only when I reboot the device. 

Any Idea what might be going wrong?

**Comment by Toolenaar** [comment] 2015-08-21 21:19
More people having this problem http://stackoverflow.com/questions/32122389/c-sharp-uwp-backgroundmediaplayer-no-sound-after-store-association

**Comment by Oblo** [comment] 2015-08-23 15:25
For me this happened after I associated the app to the store. Before that it worked perfectly.

**Comment by aarononeal** [comment] 2015-08-24 06:14
Sorry to hear you're having trouble with this. We're investigating and I'll post an update here when we have more information for you.

**Comment by Oblo** [comment] 2015-08-24 10:38
Hi Aarononeal,
Thanks for taking a look on it. If it can help, yesterday a recreated my project.
As I said in my post before, it worked perfectly.

Then I created a package which made the app association with the store.
The issue came back.

There must be something which broke something in the store association.

**Comment by aarononeal** [comment] 2015-08-25 18:15
Thanks. We're still investigating. Some reports mention this happens on Desktop. Has anyone tested whether this also happens on Phone?

**Comment by Oblo** [comment] 2015-08-25 20:33
Hi Aarononeal,
Didn't tried on phone.

**Comment by aarononeal** [comment] 2015-08-25 21:57
We have reproduced this issue on desktop. I'll let you know once we identify a root cause.

**Comment by Alovchin91** [comment] 2015-08-30 12:30
@aarononeal Any news?

**Comment by aarononeal** [comment] 2015-08-30 15:25
Running the store association wizard adds a Package.StoreAssociation.xml and updates the following fields in the .appxmanifest:

* Package Display Name
* Package Name
* Publisher ID
* Publisher Display Name
* Version

We haven't determined yet why this is causing the reported issue and why reverting the changes resolves it, but one of our engineers will be investigating this further in the coming week.

**Comment by iancona** [comment] 2015-08-30 21:25
Same problem here after store association, affecting only desktop x86 x64, not ARM, it's working perfectly on Windows 10 Mobile.

**Comment by aarononeal** [comment] 2015-08-31 17:36
For folks that can reproduce this, can you share the identity name string of your app? We're looking for a pattern. You can email me at "aaron.oneal" (you know the domain) if you prefer.

**Comment by aarononeal** [comment] 2015-08-31 22:43
We have confirmed the root cause and we are getting this fixed. Sorry about that. The workaround is to change your "Package name" to be greater than 20 characters. Please let us know if that works for you.

**Comment by Alovchin91** [comment] 2015-09-01 05:31
@aarononeal I'll be able to check this later this week. Meanwhile, will it be a fix for build 10240 via Windows Update, or something else? Thanks.

**Comment by aarononeal** [comment] 2015-09-01 05:38
I'm hoping we can get it published through Windows Update for that build but we're still working out the details.

**Comment by Alovchin91** [comment] 2015-09-01 06:50
@aarononeal Does that mean there's a chance that build 10240 won't be updated, and the fix will go to one of the next builds?

**Comment by Oblo** [comment] 2015-09-01 17:47
Is there a way to keep the identity change. When i build the store package, it's overridden by the one which doesn't work.

**Comment by aarononeal** [comment] 2015-09-02 05:37
@Alovchin91 That's possible but I'm hopeful we can backport.

@Oblo How are you setting the identity? It could be the one in your Package.StoreAssociation.xml is out of sync with your .appxmanifest.

**Comment by Oblo** [comment] 2015-09-02 09:20
I just modified the .appxmanifest.

**Comment by aarononeal** [comment] 2015-09-02 19:45
@Oblo Is it showing correctly on the Packaging tab? What if you run the store association wizard again? What command are you issuing that's triggering the store sync?

**Comment by aarononeal** [comment] 2015-09-02 20:21
@Oblo It looks like it gets overwritten when you package the app. The currently recommended workaround is to reserve a longer app name.

The computed package family name has to work out to 35 characters. This means your package name which may include a friendly organization or developer ID has to be 21, assuming the 14 character suffix that gets added.

**Comment by Oblo** [comment] 2015-09-03 08:56
@aarononeal There must be another way. My developer ID is short, I must rename the app with a 10 characters name. It is too much.

**Comment by aarononeal** [comment] 2015-09-03 17:06
@Oblo You can keep your app display name that customers see whatever you want. It's only the package name used by the store that needs to be extended until we can get the bug fixed.

**Comment by Oblo** [comment] 2015-09-04 10:49
@aarononeal This may be out of subject but, I reserved another app name and there is nowhere on the dev center where I can switch with the new one. It doesn't show itself in visual studio in the store wizard.

**Comment by aarononeal** [comment] 2015-09-08 19:54
We have a platform fix on the way so I am going to mark this issue closed. Thank you all for your assistance diagnosing and your patience. We currently expect the fix to be included in a future update to Windows 10.

The only known workaround is to use a package name >= 21 characters when associating to the store.

@Oblo I am told that when you create the package in VS there is a "Select an app name" page it should show up on.

**Closed by aarononeal** 2015-09-08 19:54 UTC

**Comment by zhengbomo** [comment] 2015-09-29 16:21
I had got the same problem, how can I rename my app, are you kidding me, has any solution for the issue now?

**Comment by Oblo** [comment] 2015-09-29 17:26
The fix still didn't came, when I recompile the app with a store association, the issue is stil here.
Very discouraging :-1:

**Comment by aarononeal** [comment] 2015-09-29 17:50
I'm sorry this bug slipped through and we disappointed you. We do have a fix on the way but it requires an OS file patch that will take a few more weeks to circulate. We're taking steps to improve this in the future. Thank you for your patience.

**Comment by jernelson7** [comment] 2016-12-09 18:51
Looks like this issue is closed a long time ago but I'm seeing the exact same issue in Windows 10 Anniversary. The suggested workaround (package name > 20 characters) did not work. Help?

**Comment by aarononeal** [comment] 2016-12-09 18:58
The bug was fixed, and if the workaround made no difference, then it's very likely you have encountered a different issue.

Please provide the following and I will try to assist:
1. The exact Windows build
2. Target platform (desktop, phone, xbox)
3. Specific steps to reproduce
4. Observed behavior and expected behavior

**Comment by tonyyyrocks39** [comment] 2017-02-19 07:15
This issue still exists.I am using insider build 15031.Sound plays in emulators but not in desktop.
If I change package name more than 20 characters it works for first time,but second time it doesnot work

**Comment by aarononeal** [comment] 2017-02-21 21:12
@tonyyyrocks39 Let's tackle that in issue #587.
