### ISSUE TITLE
VOIP sample not longer working on Fall Creators Update

### ISSUE THREAD

**Issue by wbokkers** [Microsoft/Windows-universal-samples#770] opened 2017-10-30 15:37 UTC
I got the following error on building:

Error	APPX0501	Validation error. error 80080204: App manifest validation error: Line 41, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="VoipTasks.CallRtcTask" without ActivatableClassId in windows.activatableClass.inProcessServer.

**Comment by oldnewthing** [comment] 2017-10-31 23:14
I asked the feature team to investigate.

**Comment by totoroyyb** [comment] 2017-11-16 10:34
I'm not working on this sample, but instead, I try to add background task on my own uwp app, but the complier pop up the exactly same error. OS 16299 Fall Creator Update and Visual studio version 15.4.4. It seems to be the issue around Visual Studio

**Comment by aarononeal** [comment] 2017-11-16 19:01
A Visual Studio bug strips the background audio task during packaging. A fix is in the works or you can upgrade to 15.5 preview.

The bug only affects packaging so you should still be able to run and debug locally or manually add the task back to your packaged manifest.

**Comment by totoroyyb** [comment] 2017-11-17 02:19
I've tried upgrade to 15.5 preview, and the problem is still there. Also, I cannot debug and build. Error message says "error 80080204: App manifest validation error: Line 46, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="Days.Tile.CoverTileBackgroundUpdate" without ActivatableClassId in windows.activatableClass.inProcessServer". I want to set the timer and register background task

**Comment by kwiqniss** [comment] 2017-11-17 22:13
I'm also encountering this error in builds for 16299.

**Comment by limanartem** [comment] 2017-11-21 20:03
Same issue here. Please fix ASAP

**Comment by nbevans** [comment] 2017-11-23 19:47
+1 (just a "timer" type background task as well - nothing to do with audio!)

**Comment by cc-cortes** [comment] 2017-11-24 01:19
We are currently investigating this. To confirm, creating a background task without a ServerName attribute defined is not causing this validation error, correct? The background task sample and adding a background task to a new project do not cause this validation error. I can only repro this when a ServerName has been defined in the backgroundTasks element that is pointing to an out-of-proc server.

**Comment by wbokkers** [comment] 2017-11-24 07:09
It can be solved by adding an audio trigger to the task in de manifest. De VS tooling strips this trigger from the manifest. It will be solved in the upcoming VS release.

**Comment by nbevans** [comment] 2017-11-24 11:17
No ServerName is defined - neither the BackgroundTask samples nor any of the MSDN docs indicate anything about needing to specify a ServerName.

Also when adding the task type of "audio" the error changes to this:

`error 0x80080204: Cannot register the MYPACKAGENAME package because the extension is missing an EntryPoint or StartPage attribute.`

**Comment by nbevans** [comment] 2017-11-24 12:34
Okay for me it transpired I was missing a critical thing. The class that implements `IBackgroundTask` must *MUST* be in a separate class library that is of type "Windows Runtime Component". It CANNOT be in the main .exe assembly of your project. This is the critical details that none of the docs mention - if they do, then I missed it.

Once I did this my manifest was as simple as following the samples/docs and all the other problems went away! Including the Event Viewer logs showing activation failures for the background task:

`The background task with entry point MyCompany.MyProduct.Background.Synchronization.MySyncTaskImpl and name My Sync Task failed to activate with error code 0x80131522.`

(That hex error code means the CLR type could not be found - by the way).

The only thing I added to my manifest was:
```
      <Extensions>
        <Extension Category="windows.backgroundTasks" EntryPoint="MyCompany.MyProduct.Background.Synchronization.MySyncTaskImpl">
          <BackgroundTasks>
            <Task Type="timer" />
          </BackgroundTasks>
        </Extension>
      </Extensions>
```

**Comment by erossetto** [comment] 2017-12-03 06:04
Same error here

**Comment by erossetto** [comment] 2017-12-04 22:35
After adding the "audio" workaround I'm getting:

`3>DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(41,10): error 0x80080204: Cannot register the VoIPSample-SDKSample_1.0.1.0_x64__n6q4vj2h50p3g package because the extension is missing an EntryPoint or StartPage attribute.`

Any ideas?

**Comment by cc-cortes** [comment] 2017-12-04 23:38
A bug in the manifest validation step has been identified and a fix is being put in place. As a mitigation around the validation error VOIP apps can set the Minimum Target Version for each Project (Voip, VoipBackEnd, VoipHost, VoipTasks) to an older version such as 15063 while keeping the Solution file as-is. This mitigation will be added to the VOIP sample in a future update.

**Comment by erossetto** [comment] 2018-01-08 21:04
Any updates? I'm using XAML features from FCU.

**Comment by oldnewthing** [comment] 2018-01-19 17:13
See the answer from @cc-cortes above. Set the Minimum Target Version for each of the four projects to 15063, and that will get it to pass manifest validation. This fix will be applied to the repo in the February update.

**Closed by oldnewthing** 2018-01-19 17:13 UTC
Labels: appmodel, tracking

**Comment by tqk2811** [comment] 2019-11-01 17:16
VS2019 and still this error?

**Comment by oldnewthing** [comment] 2019-11-01 17:53
The issue is not with VS, but with the SDK.

**Comment by jitendrajadav** [comment] 2020-01-03 07:26
error APPX0501: Validation error. error 80080204: App manifest validation error: Line 42, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="ShinyBackgroundTask" without ActivatableClassId in windows.activatableClass.inProcessServer.
1>

I am having still this issue I don't know is there any work around to build my application

Min Version 16299 Fall Creator update
Max Version 1903(18362)

**Comment by novinsab** [comment] 2020-07-11 17:38
I am still having the same issue as well.

**Comment by skst** [comment] 2020-12-31 19:53
I get the same error when I try to implement the 'alarm' capability following what little documentation I can find for scheduled toast notifications. The doc says I do not have to specify an _Executable_ or _EntryPoint_:

````
 <uap:Extension Category="windows.alarm" Executable="MyApp\MyApp.exe" EntryPoint="App" />
 <Extension Category="windows.backgroundTasks" Executable="MyApp\MyApp.exe" EntryPoint="NotImplemented">
	 <BackgroundTasks>
		 <Task Type="timer"/>
	 </BackgroundTasks>
 </Extension>
````

I get this error: `An unexpected error occurred. HRESULT 0x80020003`

When I add `Executable="MyApp\MyApp.exe" EntryPoint="NotImplemented"`, I get this error:

`error APPX0501: Validation error. error 80080204: App manifest validation error: Line 59, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="NotImplemented" without ActivatableClassId in windows.activatableClass.inProcessServer.`

**Comment by cay7man** [comment] 2021-01-17 13:43
I have VS 16.8.4 and I get the same error. Any fix/workaround?

**Comment by TE-B-drathnayake** [comment] 2023-02-16 00:56
In 2023 we are still having this issue.
---
1. Audio work around does not work
    It cause a different error pointed out by erossetto
    https://github.com/Microsoft/Windows-universal-samples/issues/770#issuecomment-349129815
2. Downgrading Target Min OS version does not work
    Because now in 2023 we are using so many other functions which were not available in 2017
3. I tried adding a separate Windows Runtime Component project to my solution
   But then encountered a different issue with BindServiceNameAsync()
   (I'm trying to run a StreamSocketListener in the background)
   https://stackoverflow.com/questions/75457335/uwp-steamsocketlistener-a-wildcard-address-cannot-be-used-with-a-specific-port-w

Appreciate if somebody can help with this...
