### ISSUE TITLE
Few questions related to Custom Capability example

### ISSUE THREAD

**Issue by sfq24** [Microsoft/Windows-universal-samples#948] opened 2018-07-25 21:51 UTC
Hi,
I am trying to communicate between my windows service and UWP app. Then, it seems use Custom Capability and RPC will be a reliable choice. However, I have few question and need help:
1. RpcServer.exe cannot be installed. I can build success in the C# solution. When running " RpcService. exe -install", will get an error: **Entry point not found**. How to solve this problem and install the service?
Now if i click start in UWP app, it will crash.
2. Is it possible to implement both the UWP app and service in C#? Because we need to use some C# SDK on the service side.
3. Is there any good tutorial/sample code for RPC in C#?

Thanks for your help!

**Comment by sfq24** [comment] 2018-07-25 22:01
Error:
![image](https://user-images.githubusercontent.com/20710644/43229946-5094355a-901b-11e8-8937-1382d8855ac0.png)

I also tried the CPP solution. same error above. But if you click ok, another one will show up:
![image](https://user-images.githubusercontent.com/20710644/43230002-8b258b7e-901b-11e8-8a66-d8199dae9f73.png)

**Comment by oldnewthing** [comment] 2018-07-25 22:17
Was "RpcService.exe" a typo? I don't see an "RpcService.exe" in the project. I'll assume you meant RpcServer.exe.

I don't understand why RpcServer.exe is looking for a procedure in itself. It should be getting it from a system DLL. Can you try a clean rebuild? Also, which version of the sample are you using, and which version of Windows are you deploying to?

(Writing a service in C# is out of scope for this repo. The service in the sample is really not part of the sample. It's just providing something for the sample to connect to.)

**Comment by sfq24** [comment] 2018-07-25 23:11
Hi Chen,
Thank you for your reply! 
Sorry for the typo. It should be " RpcServer.exe".
I am using the code from master branch of: https://github.com/Microsoft/Windows-universal-samples.git
My OS is Win10 10.0.14393.

I tried to clean and rebuild, but not working. I also tried to clone the repo to a new directory and still have the same problem.

Understand that this sample is meanly about the custom capability in the UWP app. But is it possible to implement RPC endpoint in a .NET based windows service for UWP app?

Thanks.

**Comment by oldnewthing** [comment] 2018-07-26 01:53
You can ask Developer Support for questions about writing services in C# and p/invoking to the necessary APIs.

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by sfq24** [comment] 2018-07-26 15:35
Sure, I will ask questions in the Developer Support. 
Please help and check  the RpcServer.exe problem. This code example will be very helpful for us if it works.

Thanks.
Song

**Comment by oldnewthing** [comment] 2018-09-09 20:32
The error message makes no sense. DeriveCapabilitySidsFromName is a function in Windows, not a function in RpcServer.exe. And RpcServer.exe isn't a dynamic link library anyway. I cannot reproduce this problem on my machine.

**Closed by oldnewthing** 2018-09-09 20:32 UTC
