### ISSUE TITLE
WebAuthenticationBroker not working

### ISSUE THREAD

**Issue by pstech2020** [Microsoft/Windows-universal-samples#528] opened 2016-11-17 05:28 UTC
WebAuthenticationBroker sample with Google is not working.

I got this error on the screen:
"We can't connect to the service you need right now .Check your network connection and try this again later."

The exception message is:
"The system cannot locate the resource specified."

I searched online, and some people have similar problems, but no solutions.

Maybe something has changed on Google provider side?

Is this sample working for anyone (as of 11/16/2016)?

I seem to remember this sample worked before.

Thanks.

**Comment by alexsorokoletov** [comment] 2016-12-27 07:16
Hi @pstech2020 
I can confirm that WebAuthenticationBroker sample is not working on Windows 10 Mobile 14977.
It works just fine on Windows 10 Desktop 14393.

**Comment by alexsorokoletov** [comment] 2016-12-27 08:57
Using [this sample](https://code.msdn.microsoft.com/windowsapps/How-to-ignore-Self-Signed-e50b89b6) HRESULT shows the error with Google is `ERROR_WINHTTP_SECURE_CHANNEL_ERROR` code `12157` ([all errors](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383770(v=vs.85).aspx))

However, ignoring this error didn't work. Mobile Edge is not opening https://google.com and https://accounts.google.com/ 
Date and time on device is correct.

**Comment by alexsorokoletov** [comment] 2016-12-29 17:54
Jen MSFT from Twitter suggested to check the url https://accounts.google.com/  in Edge in normal and private mode.
Private mode works, normal doesn't. Not sure how to relay this to the WebAuthenticationBroker.

**Comment by oldnewthing** [comment] 2017-11-01 00:42
I think this is a duplicate of #643.

**Closed by oldnewthing** 2017-11-01 00:42 UTC
Labels: identity

**Comment by alexsorokoletov** [comment] 2017-11-01 01:17
Is this issue fixed?
