### ISSUE TITLE
BasicFaceDetection sample builds but doesn't do anything on x86

### ISSUE THREAD

**Issue by adigostin** [Microsoft/Windows-universal-samples#763] opened 2017-10-24 07:22 UTC
I tried uploading a screenshot with the app window showing "Windows platform sample" and nothing else, but uploading images in Edge doesn't work either. I tried drag & drop and also the "selecting them" link.

I tried submitting the issue without the image, but the "Submit new issue" button is disabled as Edge keeps trying to upload the image.

I eventually created a new issue without attempting to upload the screenshot.

**Comment by adigostin** [comment] 2017-10-24 14:36
![screenshot](https://user-images.githubusercontent.com/7842314/31949382-db96c526-b8e1-11e7-8303-f8110f7e4b5d.png)

**Comment by timkeosa** [comment] 2017-10-24 18:52
Hi adigostin,

I'm looking into this, but so far the sample seems to be working fine for me. I can reproduce this behavior when debugging the sample for the first time and VS is loading all the symbols, but I don't believe that's the issue you're having. However, perhaps the VS debugger is getting "stuck" on something.

So, some follow-up questions:

Does this happen when running the sample without debugging, i.e. Ctrl+F5?
Does this happen for other versions for this sample, e.g. C# version?
Does this happen for other samples?

Thanks.

**Comment by adigostin** [comment] 2017-10-26 06:40
Hi Tim,

I tried this again and it turns out my problem is actually loading the symbol files. So there's no problem with the sample code.

(Loading Windows.UI.Xaml is extremely slow. Pressing Escape to cancel loading removes that "Loading..." message, makes the VS UI responsive, and this tricks me into believing that VS actually cancels the loading.)

Thanks,
Adi

**Comment by timkeosa** [comment] 2017-10-26 15:30
Glad you're able to figure out the problem (I've also been bitten by VS symbols).

Could you please Close this issue?
Thanks.

**Closed** 2017-10-26 15:56 UTC
