### ISSUE TITLE
CustomSerialDeviceAccess example is not working

### ISSUE THREAD

**Issue by i3anaan** [Microsoft/Windows-universal-samples#917] opened 2018-06-13 13:55 UTC
Upon selecting a serial port to connect to the following error gets thrown:
```
Exception is about to be caught by JavaScript library code at line 161, column 25 in ms-appx://microsoft.sdksamples.customserialdeviceaccess.js/js/eventHandlerForDevice.js
0x80070002 - JavaScript runtime error: The system cannot find the file specified.
```

Which happens in this method:
```
Windows.Devices.Enumeration.DeviceAccessInformation.createFromId(deviceInfo.id)
```

This happened with trying several serial ports, where other applications had no problem connecting to the serial port.
In part due to the lack of information (which file is missing?) in the exception it is unclear what the exact issue is. This is preventing us from using the library

**Comment by oldnewthing** [comment] 2018-06-13 19:46
Duplicate of #559

**Closed by oldnewthing** 2018-06-13 19:46 UTC

**Comment by i3anaan** [comment] 2018-06-20 12:59
@oldnewthing Thank you for your (quick) response, but I would like ask you to take a second look at my case, as I believe it is not simply a duplicate of #559 

I have a screenshot attached below about the setup I used to test with the serial port.
As you can see there are 3 ports, all three of which return the error as mentioned in this issue. I quote the documentation:
> may have a serial device whose DeviceInformation.Name property is set to the machine name.

This, to me, sounds like this can only be 1 device and not 3 (like I am experiencing).

To elaborate on the screenshot below:
- 2 Virtual COM ports have been added (COM1 and COM2) using a [virtual serial port driver](https://www.eltima.com/products/vspdxp/)
- [GPSFeed+](https://sourceforge.net/projects/gpsfeed/) is used to fake a GPS output on the serial port (GPS strings are also our target usage)
- [Termite](https://www.compuphase.com/software_termite.htm) Is used to confirm that the sending by gpsfeed+ succeeds.

Using this I tested all 3 devices that are shown in the sample app, with and without termite/gpsfeed+ 'locking' the COM port. In all cases the error as mentioned in this issue occurs.

**Now I can see two things where this could go wrong**
- **The disclaimer in the documentation can be for more than 1 device** ,in which case I suggest to update this in the documentation
- **This sample does not play well with virtual COM ports**, in which case I again suggest to update the documentation to reflect this (and an alternative way to test/use this during development would be very much appreciated!)

![image](https://user-images.githubusercontent.com/2911348/41658449-ab15efa0-7496-11e8-820e-e13403d74997.png)
