### ISSUE TITLE
DWriteTextLayoutCloudFont doesn’t work, leaks memory

### ISSUE THREAD

**Issue by chris-morgan** [Microsoft/Windows-universal-samples#465] opened 2016-08-18 02:13 UTC
I just tried running the DWriteTextLayoutCloudFont sample, but it’s not actually replacing the font ever (after leaving it for many minutes it’s still listing the font being used as not the right one) and each time I switch between the three documents memory usage goes up by around five megabytes and doesn’t come back down—it’s leaking like a sieve.

Visual Studio Enterprise 15 Preview 3, 64-bit, running on the local machine.

**Comment by PreedaOla** [comment] 2016-08-26 01:00
Hi Chris,

Have you tried running the PowerShell script, ClearDownloadableFontCache.ps1, to reset the state of the downloadable font mechanism (clearing cached data)? Instructions for using this script are given in the sample app.

Please let us know if you still encounter the problem?

**Comment by PeterCon** [comment] 2017-03-11 01:55
I tried the app and it appears to be working --- downloading the remote fonts as expected. Obviously, internet connectivity is needed. Another possible reason why it might not work is the remote-font functionality may be disabled. For example, I think that Server has this disabled by default.

Regarding the memory leak, the root cause has been diagnosed: In code behind for each of the Document 1, Document 2 and Document 3 pages, there are three event handlers that get hooked up to events, but only one of these is getting unregistered when the page goes out of focus. Each handler is capturing a reference to the page object. So, when the page goes out of focus and is going out of scope, there are still two references to it, and so it doesn't get destructed. An easy fix will be to add member variables for two additional event tokens, and then unregister them in the OnNavigatedFrom method, just like the one already being unregistered. We'll try to get this fixed before long.

**Comment by oldnewthing** [comment] 2017-03-16 04:03
Fix went out today. Thanks for reporting.

**Closed by oldnewthing** 2017-03-16 04:03 UTC
Labels: graphics
