### ISSUE TITLE
SystemMediaTransportControls - Play/Pause controls grayed out when CommandManager.IsEnabled == false

### ISSUE THREAD

**Issue by planetarian** [Microsoft/Windows-universal-samples#476] opened 2016-09-02 21:37 UTC
I'm kind of new to all this, so please forgive any poor etiquette on my part, but here we go.
I discovered this problem within my own project where I'm trying to design a player for a streaming radio service that can detect when song changes occur and update the transport controls automatically.
I ended up looking at this sample as a reference for manually controlling the seek bar, and found this issue when trying the method myself in my own project. Wondering if maybe I wasn't doing anything wrong, and if perhaps the sample exhibited the same problem, I tried running it and sure enough, it has the same issue. This perhaps suggests it's a framework issue, and not necessarily a problem with the sample itself, but I'm not sure where else to inquire about this.

Tested on two PCs running 14393.82, and my Lumia 950XL running 14905 Insider. Going to install the cumulative update on the non-insider desktop and see if the behavior changes (I'm guessing not).

**Procedure:**
1) clone https://github.com/Microsoft/Windows-universal-samples
2) open SystemMediaTransportControls.sln
3) change target to x64 and start debugging
4) click 'select files' and open an mp3
**Expected Result:**
Media controls operate normally.
**Actual Result:**
Media begins playing, Play/Pause in the application window are grayed out and cannot be interacted with. Play/Pause in the volume OSD and lock screen work fine, as do keyboard media controls. It is only the transport controls on the MediaPlayerElement that are grayed out.

other related issue: https://github.com/Microsoft/Windows-universal-samples/issues/477

related forum post:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/fa6a9b91-a154-4467-ae80-73293454a218/uwp143938214905-mediaelement-playpause-controls-grayed-out-when-commandmanagerisenabled-?forum=wpdevelop

edit: said MediaElement, meant MediaPlayerElement.

**Comment by aarononeal** [comment] 2016-10-03 21:44
Here's the scoop on this issue.

The sample disables CommandManager which breaks the link to the built-in MediaTransportControls attached to the MediaPlayerElement.

It's currently by design that disabling the CommandManager breaks the link to the controls. Apps that disable CommandManager are expected to implement custom app controls, and if they're also background capable, the app must also handle SystemMediaTransportControls events.

Therefore, we have a sample bug to fix. The sample should be implementing custom app controls instead of trying to use the built-in ones. We're opening an internal bug to track and will close this one.

Please note, we expect most apps to leave CommandManager enabled and to use it instead of manually integrating with SystemMediaTransportControls as this sample shows.

**Closed by aarononeal** 2016-10-03 21:44 UTC
Labels: media
