### ISSUE TITLE
RemoteSystems example throws HRESULT E_FAIL exception as soon as Search for Devices is clicked

### ISSUE THREAD

**Issue by manjia** [Microsoft/Windows-universal-samples#683] opened 2017-06-27 13:40 UTC
RemoteSystem.CreateWatcher() call always raises a COMException, the stacktrace doesn't give me any clue about what is happening..

**Comment by oldnewthing** [comment] 2017-06-27 19:44
Which version of the sample are you running? Have you modified the samples in any way? (Make sure you didn't delete the "remoteSystem" capability from the manifest.)

**Comment by manjia** [comment] 2017-06-28 08:31
I'm using the win10-1607 branch on VS2015 (I cannot afford to switch to VS2017 because I would have compatibility issues with other projects I'm working on), I did not modify the sample in any way and the remoteSystem capability is definitely there, the method that raises the exception is the RemoteSystem.CreateWatcher(); (with no arguments)

**Comment by oldnewthing** [comment] 2017-06-28 15:47
Okay, thanks for the details. I've asked the feature team to look in to this. Are there any RoOriginateError messages in the debugger?

**Comment by manjia** [comment] 2017-06-28 15:55
This is the most details i can extract from vs:

![senza-titolo-2](https://user-images.githubusercontent.com/4418298/27647019-89b0fe66-5c2a-11e7-89b0-53627c73a025.png)

I also confirm this happens even on a newly created app by just invoking RemoteSystem.CreateWatcher(), has anybody tested this method before publishing it?

**Comment by manjia** [comment] 2017-06-30 15:15
I solved my issue using non-microsoft software to establish the connection I needed, so I don't need  RemoteSystem anymore. 
Thanks a lot for the quick response (sarcasm), as always the support from microsoft people is terrible.

**Comment by oldnewthing** [comment] 2017-11-18 01:55
The feature team says that they cannot reproduce the problem, and there's not enough information in the report to diagnose what may be happening on your system. The team says that they've made many improvements to RemoteSystem, so it's possible that this issue has already been fixed in the Fall Creators Update.

**Closed by oldnewthing** 2017-11-18 01:55 UTC
Labels: networking-and-storage, tracking
