### ISSUE TITLE
XamlCommanding Scenario 8 is broken on RS2

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Windows-universal-samples#644] opened 2017-05-04 20:20 UTC
OS Version	10.0.15063 Build 15063

1. Open `Samples\XamlCommanding\cs\Commanding.sln` in VS 2017.
2. Start Debugging
3. Navigate to Scenario 8 (Command Reflow)

App hangs.

**Comment by oldnewthing** [comment] 2017-10-31 19:38
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment] 2017-11-01 01:18
Duplicate of #250.

**Closed by oldnewthing** 2017-11-01 01:18 UTC
Labels: tracking, xaml
