### ISSUE TITLE
Inputting voice fails to produce results

### ISSUE THREAD

**Issue by shirobusa1997** [microsoft/Windows-universal-samples#1385] opened 2023-04-11 01:05 UTC
**Which sample are you reporting a bug in?**

Example: PredefinedDictationGrammar

**Describe the bug**

_I am learning English, so I am sure there are many oddities in the text.
Sorry to all the support people._

When I run the sample with the sample code unchanged and input audio, I get no results and speech recognition fails.
When I try the network with both fixed and mobile lines, there is no change, and the microphone authority is obtained correctly.

I am developing an application in Unity that uses the Windows.Media.SpeechRecognition Runtime API in the same way, but only the speech recognition is not working, including older projects.
This leads me to believe that it is a temporary problem on the service side, but is there any fix I can do?

**To Reproduce**
1. Download latest samples from this repository
2. Build and deploy samples for x64 platform in debug mode
3. Select "4)Predefined Dectation Grammer" from left side menu
4. Select "日本語 (Japanese)" Language
5. Push "with UI" button and speech something
6. Return result "Speech Recognition Failed, Status: Unknown"

**Expected behavior**
Speech recognition should succeed and a string of the input speech should be obtained.

**Screenshots**
![image](https://user-images.githubusercontent.com/8602558/231024045-b500b87e-8101-4fae-bc3c-c37f1f4f6df1.png)

**Configuration**
OS : Windows 10 22H2 (OS Build 19045.2728)
IDE : Visual Studio 2022 Version 17.4.4
Target Version : Windows 10 Version 2004 (10.0; Build 19041)

**Comment by koizuka** [comment] 2023-04-11 08:26
Not only with the "4) Predefined Dictation Grammar" but also with the "8) Continuous Dictation," the same phenomenon occurs.
This happens not only in Japanese but also in English when tested.
I noticed this issue around the evening of April 8th Japan Standard Time, so it has likely been happening since then.
Maybe something is going on server-side?

**Comment by kenter1** [comment] 2023-04-12 18:36
Same issue and I use WinRT api for the Continous Recognition

**Comment by naveenrobo** [comment] 2023-04-13 05:23
Still now same issue. We have a application deployed on production to use the Continuous Dictation. For last 3 days it doesn't seem to work. It is an Unity Application which inturn uses Windows Media Speech Recognizer. We thought it was a issue Unity. Now we checked this sample and this also it is not working.

**Comment by livioenrico** [comment] 2023-04-16 12:45
- Starting from the beginning of April 2023, the the online speech dictation has stopped responding on Windows systems worldwide. Tests have been conducted in numerous countries, including Europe, China, and India, and you can verify it on your own PC in just a few seconds by pressing the WINDOWS - H keys.

- It would be advisable for Microsoft to issue an official statement and encourage its users to be patient while the problem is being resolved. Currently, millions of users are following incorrect advice, such as reinstalling the microphone driver, doing a clean restart, or modifying the system registry. And many users have even reinstalled Windows without success.

**Comment by livioenrico** [comment] 2023-04-16 12:45
- We have dedicated a lot of time to the development of the Theremino GPT application, which allows people with various disabilities, including the blind, to use the PC through voice commands.

- Until a few days ago, these users could use Skype to call their relatives, control home devices, or have friendly conversations with an assistant who could understand their difficulties and find appropriate solutions.

- Currently, these users, who are already facing many difficulties, have been left to themselves due to the failure to repair the online voice dictation server.

- We are disappointed that Microsoft has not been able to solve the problem after more than ten days.

- Please let us know if we can still rely on these functions, otherwise we will be forced to consider alternatives such as Google Speech Recognition.

**Comment by RobertVS-MS** [comment] 2023-04-18 23:57
Hey all...   we are currently attempting to track this down and understand more about the problem.   We have seen reports of this problem start to resolve over the last couple of days, so if you are still experiencing the problem here please respond back so we can determine an appropriate way to collect additional information from you.

**Comment by koizuka** [comment] 2023-04-19 04:37
@RobertVS-MS
I tried testing again and the issue still persists in both my product and the Microsoft sample code...

**Comment by RobertVS-MS** [comment] 2023-04-19 13:55
> @RobertVS-MS I tried testing again and the issue still persists in both my product and the Microsoft sample code...

@koizuka - Are you able to open a case with us via our support teams?   You can do that via the following:   https://developer.microsoft.com/en-us/windows/support/?tabs=Contact-us

Select the option for UWP App Development.  In the case description, you can reference the UWP Speech Sample, the link to this thread and that you are working with RobertVS-MS.   What I am ultimately going to need is a few traces, and ideally a time travel debug.   Having the case open will allow for me to provide you files to capture these scenarios as well as have you upload these back to us securely.

Let me know if this is possible

**Comment by livioenrico** [comment] 2023-04-19 15:21
We are testing every day on numerous different computers, with 32-bit and 64-bit operating systems, in various languages including American English, Italian, and Chinese, with the latest builds of Windows 10 (22H2 19045.2846) and also on less recent builds.

We also test the on-screen keyboard microphone and using the WINDOWS + H keys.

Among the tests, we also use the "SpeechRecognitionAndSynthesis" example found in Microsoft's official SDKs.

We also have applications written by us in CSharp for Desktop and UWP.

In all cases, using the classes of System.Speech.Recognition everything goes well, but the callbacks OnSpeechRecognized and OnSpeechHypothesized are never called.

All these examples worked perfectly on all PCs until a month ago.

------

If it is useful we opened the following cases:
 # 1052228853 (12 April 2023)  
 # 1052363017 (15 April 2023)  
 # 1052430024 (17 April 2023)

**Comment by RobertVS-MS** [comment] 2023-04-19 16:27
> We are testing every day on numerous different computers, with 32-bit and 64-bit operating systems, in various languages including American English, Italian, and Chinese, with the latest builds of Windows 10 (22H2 19045.2846) and also on less recent builds.
> 
> We also test the on-screen keyboard microphone and using the WINDOWS + H keys.
> 
> Among the tests, we also use the "SpeechRecognitionAndSynthesis" example found in Microsoft's official SDKs.
> 
> We also have applications written by us in CSharp for Desktop and UWP.
> 
> In all cases, using the classes of System.Speech.Recognition everything goes well, but the callbacks OnSpeechRecognized and OnSpeechHypothesized are never called.
> 
> All these examples worked perfectly on all PCs until a month ago.
> 
> If it is useful we opened the following cases: 1052228853 (12 April 2023) 1052363017 (15 April 2023) 1052430024 (17 April 2023)

@livioenrico - I'm not fully sure I recognize those case formats.   If you can tell me how you submitted them, I can try to figure out where they came from to see if they have additional information

**Comment by livioenrico** [comment] 2023-04-19 16:48
They was references to chat with the Microsoft Technical support.

But there is a good new !
I tested the dictation now and it is working !!!
I've tried it already on numerous computers including some 32 bit tablets as well and it works again on all of them. 

Tech support told me they would send a patch within a week but they didn't, the system started working again without updating the PCs.

So it is clear that the defect was on the server.

Now it would be very helpful to know some references on what they did to fix it. I say this because the same defect had occurred in mid 2021 and also January 2022 and each time it takes many days of searching and trying to fix it.
So it would be helpful to have some precise reference so that we can tell Microsoft what to do next time it happens.

**Comment by koizuka** [comment] 2023-04-19 16:53
hmm... still not working on my environment....

**Comment by livioenrico** [comment] 2023-04-19 16:56
Dear koizuka, where are you ?have you tested with Windows + H ?

**Comment by koizuka** [comment] 2023-04-19 17:08
@livioenrico, I'm in Japan. My system is Windows 10 and,
When I press Windows+H, the Microsoft Text Input Application notifies me that dictation cannot be used for the current language (Japanese), so I haven't tested it. In the same environment, I was previously able to use dictation from UWP applications.

**Comment by livioenrico** [comment] 2023-04-19 17:13
Ok, the same was for me.
But now it works correctly on all the PC in Italy.

Others said it started working again in the past few days but here it still didn't work. So I'm starting to think that there are numerous servers located in various countries and they are restoring them one after another.

**Comment by koizuka** [comment] 2023-04-19 17:19
Sure, then maybe Japan's issue will be fixed soon too. I'll keep an eye on it for a bit.

**Comment by nmanis** [comment] 2023-04-19 18:02
Thanks for the updates and this matches what we see in Europe now too (working again).  We do have support staff looking at this from Japan side too.

Will update once we do get more information to pass along including what we can advise for root cause.

**Comment by shirobusa1997** [comment] 2023-04-20 00:07
@RobertVS-MS 
Thank you for your reply.

We are creating an application for UWP (Hololens2), similar to the first post in this Issue, that uses the Windows.Media.SpeechRecognition Runtime API, which is a Windows Runtime API. However, about a week or two ago, the service suddenly became unavailable and the results of the speech recognition could not be obtained from the service.

I also tested with the speech recognition sample "PredefinedDictationGrammar" in the Windows-universal-samples repository, but it is not returning any speech recognition results as well.

I checked again this morning (4/20 AM 9:00 JST), but the condition has not improved.

**Comment by livioenrico** [comment] 2023-04-20 12:08
It seems to be resolved for everyone, all around the world, let's hope it doesn't happen again!
Unfortunately, it has already happened at least three times (April 2023, January 2022, summer 2021)
So let's make a summary to help Microsoft next time.

**SYMPTOMS**
- The "Online Voice Typing" stops working on all Windows 10 computers worldwide.
- The affected systems are Windows 10 Home and Windows 10 Pro, both 64-bit and 32-bit.
- Do not confuse this with "Voice Recognition" which still works (but is terrible).
- Dictation in Office 365 and Cortana continues to work.
- Dictation in Office 2019 and other Desktop or UWP applications does not work.
- Dictation does not work in our desktop application Theremino_GPT (based on OpenAI).

**TESTS TO REPRODUCE THE PROBLEM**
- Using the WINDOWS + H keys opens the control but does not write in Notepad.
- The WINDOWS + H control after about 30 seconds says "An error occurred. Try again later"
- The on-screen keyboard microphone also produces the same results as WINDOWS + H
- CSharp applications for desktop and UWP also do not work.
- The System.Speech.Recognition classes do not return errors,
  but the OnSpeechRecognized and OnSpeechHypothesized callbacks are never called.
- All these examples worked well until the day the problem started.

**NON-WORKING SOLUTIONS**
Microsoft in these cases suggests various changes but: DO NOT FOLLOW THESE TIPS
- Reinstall the microphone driver.
- Change the user or create a new user.
- Download and install system updates.
- Tinker with the registry in various ways or run commands in the console.
- Reinstall Windows.

**HOW THE PROBLEM WAS SOLVED**
- In April 2023, the bug lasted about two weeks.
- Between April 18th and 20th, all Windows 10 computers worldwide started working again.
- In some countries, it took longer, so it seems there are different servers.
- All PCs started working again without restarting and without receiving updates.
- Therefore, this problem is definitely on Microsoft's servers.

It would be greatly appreciated if someone from Microsoft could add some references below, so as to facilitate the solution the next time the same problem occurs.

**Comment by nmanis** [comment] 2023-04-20 12:47
> It seems the issue has not yet been resolved in Japan....

Thank you for confirmation & matches what we are debugging.  Thanks again & will post back once we get to clear state

**Comment by RobertVS-MS** [comment] 2023-04-20 18:12
> It seems the issue has not yet been resolved in Japan....

Can you try now?   We're seeing some of our repros getting resolved now.

**Comment by koizuka** [comment] 2023-04-20 18:15
@RobertVS-MS now it's working!

**Comment by shirobusa1997** [comment] 2023-04-21 00:07
To all who participated in this discussion, thank you for your cooperation in this matter.
I have confirmed that speech recognition is possible in my environment, both with my own application and with the samples in this repository.

**Comment by livioenrico** [comment] 2023-04-21 06:42
Thank you all !!!
The quality of voice dictation ( Windows.Media.SpeechRecognition ) is great. It can recognize without errors even in terrible audio conditions.
This is an important component that greatly elevates the Windows Systems value!

**Comment by nmanis** [comment] 2023-04-21 13:02
Thank you for the reports and assistance.

For root cause, we have determined that an intermediate service component used in the legacy Windows Dictation experience failed to communicate properly with the speech recognition service, thereby causing speech recognition to fail during transcription.  Service was fully restored across all regions on 16:40 UTC on 20 Apr. 2023.

**Comment by RobertVS-MS** [comment] 2023-04-21 14:43
I don't have permission(s) to close an issue, but please do consider this resolved.  If similar symptoms are found in the future, please lets treat it via a new issue.

**Closed** 2023-04-21 15:44 UTC
Labels: bug
