### ISSUE TITLE
Cannot Read Mifaire Ultralight Standard NFC Card

### ISSUE THREAD

**Issue by maynee** [Microsoft/Windows-universal-samples#329] opened 2016-03-18 09:38 UTC
The sample app for Nfc is able to read Ultralight C cards ok. However, when presenting a standard Ultralight the app errors out with exception "Failure reading MIFARE Ultralight card, ApduResponse SW=6C01 (Unknown)".
Setting a breakpoint immediately after the line "MifareUltralight.AccessHandler mifareULAccess = new MifareUltralight.AccessHandler(connection);" and waiting for around 1 second before resuming allows the card to be read. Albeit, the app displays the card name as a "MifaireUltralightC" rather than a standard MifaireUltralight.
I've tried suspending the thread after the line shown above, but that doesn't resolve the problem. Only setting a breakpoint, waiting then resuming works.

**Comment by marklan** [comment] 2016-05-20 17:15
Is this happening on an actual hardware phone (not the phone emulator or desktop)? If so, this could be caused by a bug in the in-box NFC driver on phone, where the driver was not properly reading Mifare Ultralight cards but was reading Ultralight C cards just fine, as you said. This bug has been fixed and will be in the next release of Windows 10 Mobile.

**Comment by oldnewthing** [comment] 2016-06-22 21:37
Closed due to no response.

**Closed by oldnewthing** 2016-06-22 21:37 UTC
Labels: mobile-connectivity
