### ISSUE TITLE
ListView sample - drag and drop problem

### ISSUE THREAD

**Issue by mursel** [Microsoft/Windows-universal-samples#1014] opened 2018-11-12 12:08 UTC
A Simple ListView with Selection support crashes when I try to drag and drop items within list.
There are two events logged with following content:

Event ID: 1000, Application Error
Faulting application name: AppUIBasics.exe, version: 1.0.0.0, time stamp: 0x5bce4816
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17134.81, time stamp: 0x4f4899f8
Exception code: 0xc000027b
Fault offset: 0x00000000006a4e02
Faulting process id: 0x4408
Faulting application start time: 0x01d47a7bdebfe050
Faulting application path: C:\Program Files\WindowsApps\Microsoft.XAMLControlsGallery_1.2.3.0_x64__8wekyb3d8bbwe\AppUIBasics.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 5baaeb65-d614-4d97-a784-5b640ee9dd47
Faulting package full name: Microsoft.XAMLControlsGallery_1.2.3.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Event ID: 1001, Windows Error Reporting
Fault bucket 1477994731545081553, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.XAMLControlsGallery_1.2.3.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.0.0.0
P4: 5bce4816
P5: StackHash12_282
P6: 0.0.0.0
P7: 00000000
P8: 80004001
P9: 0
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A8D.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8CC1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8CE1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8CDF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D0F.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.XAMLCo_a4fe3ed4d6daf7ffeda2b6b3f5b58dd38edc9a1_ac23c865_63f093f3

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5baaeb65-d614-4d97-a784-5b640ee9dd47
Report Status: 2147487744
Hashed bucket: a90be151026a4b1e3482e460a9a4b6d1
Cab Guid: 0

**Comment by EddieLotter** [comment] 2018-11-28 03:02
I can confirm that this is happening in version 1809 build 17763.134

**Comment by oldnewthing** [comment] 2018-11-29 00:32
Okay, I had to explore a bit but I figured out that this is happening in the XAML UI Basics sample, in the ListView page, when you drag/drop within the first listview on the page. That's because that particular ListView sets itself as CanReorderItems="True", but the data source is read-only. I'll ask the feature team how they want to address this.

**Comment by oldnewthing** [comment] 2018-11-29 02:09
Okay, I have a fix. Will be in the next update.

**Closed by oldnewthing** 2018-11-29 02:09 UTC
Labels: tracking, xaml

**Comment by oldnewthing** [comment] 2018-12-04 20:18
The fix is now live in the [XAML Controls Gallery](https://github.com/Microsoft/Xaml-Controls-Gallery/pull/8).
