### ISSUE TITLE
Background audio not so background

### ISSUE THREAD

**Issue by mcosmin222** [Microsoft/Windows-universal-samples#449] opened 2016-08-07 10:31 UTC
using the new epic sample exemplifying the new epic (failure of) 1 process background audio, one can easily find the following bug:

start playback.
close app from task manager
app stops playing.

Either the configuration is incomplete, or the new system sucks.
Either way, please don't give this sample as the new and improved way of doing background audio, because it is neither.

**Comment by aarononeal** [comment] 2016-08-07 17:29
You're mistaken. This behavior is by design. It's also no different than any other platform.

Explicitly terminating a process should never continue to use system resources, including playing audio.

There is a difference between explicitly terminating an app as you appear to have done, implicitly terminating an app due to system policy, and suspending an app due to system policy.
Background audio is specifically *not* closing an app and letting the process continue to run and play music in the background--neither suspending nor terminating.

**Closed by aarononeal** 2016-08-07 17:29 UTC
Labels: media
