### ISSUE TITLE
BackgroundAudio Taskbar Thumbnail Playback Controls Present but Disabled

### ISSUE THREAD

**Issue by LtCmdrKeene** [Microsoft/Windows-universal-samples#309] opened 2016-02-25 02:16 UTC
The BackgroundAudio sample contains playback controls in the taskbar preview thumbnail, but they are disabled. Are these out of scope of the sample, and if so should they be removed?

**Comment by aarononeal** [comment] 2016-02-25 04:09
There is no way for the app to specifically remove them. They are disabled due to a current platform bug that will be addressed in a future update. For now the workaround is to implement the controls a second time but in the foreground app using SystemMediaTransportControls.GetForCurrentView().

**Closed by aarononeal** 2016-02-25 04:09 UTC

**Comment by clinton05** [comment] 2016-06-05 14:54
the work around does not work.
Furthermore, none of the samples have this working either.

suggest that this is reopened

**Comment by aarononeal** [comment] 2016-06-05 15:42
Do you see the controls in Groove?

Sorry you're having trouble getting it working, but the root cause is a platform bug which we believe will be corrected in the Anniversary Update. This venue is for tracking sample issues and we don't intend at this time to implement the workaround for this but rather fix the platform issue.

For OS bugs and development support:
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by clinton05** [comment] 2016-06-05 15:52
ok, but focusing on the work around. I've seen groove and yes it is working, is it using some undocumented API? SystemMediaTransportControls.GetForCurrentView() does not work and the sample title "SystemMediaTransportControls" also does not work.

**Comment by clinton05** [comment] 2016-06-06 06:47
Sorry work around does work.

This similar issue helped me
https://github.com/Microsoft/Windows-universal-samples/issues/100

**Comment by aarononeal** [comment] 2016-06-06 14:51
Thanks for confirming and linking up to that other issue report. Groove is currently using this workaround as well and we're working with the Windows shell team on a better solution for the future.
