### ISSUE TITLE
XamlDragAndDrop Crashes on Mobile Emulator (10240 SDK)

### ISSUE THREAD

**Issue by csnazell** [Microsoft/Windows-universal-samples#185] opened 2015-10-14 13:55 UTC
Dragging & dropping between lists on the "Enable Drag and Drop of ListView items" page crashes  app when run on mobile emulator (10240 SDK).

Steps To Reproduce:

1. Build XamlDragAndDrop and deploy to simulator.

2. Select Enable Drag and Drop of ListView items.

3. Attempt to drag items from List of items to selection list.

Reported Exception:

> 0xC0000005 occurred
Message: Exception thrown at 0x68C04AAB (Windows.UI.Xaml.dll) in DragAndDropSampleManaged.exe: 0xC0000005: Access violation writing location 0x0000003C.

Call Stack:

>	Windows.UI.Xaml.dll!DirectUI::XamlMobileDragOperation::EndOperation(Windows::ApplicationModel::DataTransfer::DataPackageOperation result) Line 393	C++
 	Windows.UI.Xaml.dll!DirectUI::XamlMobileDragOperation::RaiseDrop::__l25::<lambda>(Windows::Foundation::IAsyncOperation<enum Windows::ApplicationModel::DataTransfer::DataPackageOperation> * pOp, ABI::Windows::Foundation::AsyncStatus) Line 373	C++
 	Windows.UI.Xaml.dll!Microsoft::WRL::Details::InvokeHelper<Windows::Foundation::IAsyncOperationCompletedHandler<enum Windows::ApplicationModel::DataTransfer::DataPackageOperation>,HRESULT <lambda>(Windows::Foundation::IAsyncOperation<enum Windows::ApplicationModel::DataTransfer::DataPackageOperation> *, ABI::Windows::Foundation::AsyncStatus),2>::Invoke(Windows::Foundation::IAsyncOperation<enum Windows::ApplicationModel::DataTransfer::DataPackageOperation> * arg1, ABI::Windows::Foundation::AsyncStatus arg2) Line 270	C++
 	Windows.UI.Xaml.dll!Microsoft::WRL::AsyncBase<Windows::Foundation::IAsyncOperationCompletedHandler<enum Windows::ApplicationModel::DataTransfer::DataPackageOperation>,Microsoft::WRL::Details::Nil,1,Microsoft::WRL::AsyncOptions<-1,0,GUID_CAUSALITY_WINDOWS_PLATFORM_ID,2> >::FireCompletion() Line 766	C++
 	Windows.UI.Xaml.dll!DirectUI::RaiseDragDropEventAsyncOperation::OnCustomVisualSetUp(Windows::Foundation::IAsyncAction * __formal, ABI::Windows::Foundation::AsyncStatus status) Line 170	C++
 	Windows.UI.Xaml.dll!DirectUI::RaiseDragDropEventAsyncOperation::SetupCustomDragVisual() Line 97	C++
 	Windows.UI.Xaml.dll!DirectUI::RaiseDragDropEventAsyncOperation::OnRaiseDragDropCompleted(Windows::Foundation::IAsyncAction * __formal, ABI::Windows::Foundation::AsyncStatus status) Line 51	C++
 	Windows.UI.Xaml.dll!`Microsoft::WRL::Callback<Windows::Foundation::ITypedEventHandler<Windows::UI::Core::CoreWindow *,IInspectable *>,DirectUI::Window,Windows::UI::Core::ICoreWindow *,IInspectable *>'::`2'::ComObject::Invoke(Windows::UI::Core::ICoreWindow * arg1, IInspectable * arg2) Line 654	C++
 	Windows.UI.dll!Microsoft::WRL::AsyncBase<Windows::Foundation::IAsyncActionCompletedHandler,Microsoft::WRL::Details::Nil,1,Microsoft::WRL::AsyncCausalityOptions<&Windows::UI::Core::CoreAsyncActionName,GUID_CAUSALITY_WINDOWS_PLATFORM_ID,2> >::FireCompletion() Line 768	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessInvokeItem() Line 1149	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage(int bDrainQueue, int * pbAnyMessages) Line 210	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessages(void * hEventWait) Line 426	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents(Windows::UI::Core::CoreProcessEventsOption options) Line 535	C++
 	Windows.UI.Xaml.dll!DirectUI::FrameworkView::Run() Line 102	C++
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run(void)	Unknown
 	twinapi.appcore.dll!CTSimpleArray<struct COSTaskCompletion::TaskContext *,4294967294,class CTPolicyCoTaskMem<struct COSTaskCompletion::TaskContext *>,class CSimpleArrayStandardCompareHelper<struct COSTaskCompletion::TaskContext *>,class CSimpleArrayStandardMergeHelper<struct COSTaskCompletion::TaskContext *> >::RemoveAt(unsigned int)	Unknown
 	SHCore.dll!_SHCreateThreadRef@8()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

Disassembly:

> --- d:\th\windows\dxaml\xcp\dxaml\lib\xamlmobiledragoperation.cpp --------------
 68C04A91  mov         edi,edi  
 68C04A93  push        ebp  
 68C04A94  mov         ebp,esp  
 68C04A96  push        ecx  
 68C04A97  push        ecx  
 68C04A98  mov         eax,ecx  
 68C04A9A  push        ebx  
 68C04A9B  push        esi  
 68C04A9C  push        edi  
 68C04A9D  mov         edx,dword ptr [eax+20h]  
 68C04AA0  mov         dword ptr [ebp-8],eax  
 68C04AA3  mov         eax,dword ptr [result]  
 68C04AA6  push        1  
 68C04AA8  lea         ebx,[edx+8]  
*68C04AAB  mov         dword ptr [edx+3Ch],eax  
 68C04AAE  mov         ecx,ebx  
 68C04AB0  call        Microsoft::WRL::AsyncBase<Windows::Foundation::IAsyncActionCompletedHandler,Microsoft::WRL::Details::Nil,1,Microsoft::WRL::AsyncCausalityOptions<&DirectUI::DragVisualRenderAsyncName,GUID_CAUSALITY_WINDOWS_PLATFORM_ID,2> >::TransitionToState (68C089DAh)  
 68C04AB5  mov         eax,dword ptr [ebx]  
 68C04AB7  mov         edi,esp  
 68C04AB9  mov         esi,dword ptr [eax+40h]  
 68C04ABC  mov         ecx,esi  
 68C04ABE  call        dword ptr ds:[68F0D6ACh]  
 68C04AC4  mov         ecx,ebx  
 68C04AC6  call        esi  
 68C04AC8  cmp         edi,esp  
 68C04ACA  je          DirectUI::XamlMobileDragOperation::EndOperation+42h (68C04AD3h)  
 68C04ACC  mov         ecx,4  
 68C04AD1  int         29h  
 68C04AD3  mov         esi,eax  
 68C04AD5  test        esi,esi  
 68C04AD7  js          DirectUI::XamlMobileDragOperation::EndOperation+94h (68C04B25h)  
 68C04AD9  and         dword ptr [ebp-4],0  
 68C04ADD  lea         ecx,[ebp-4]  
 68C04AE0  call        DXamlInstanceStorage::GetValue (687824D0h)  
 68C04AE5  mov         eax,dword ptr [ebp-4]  
 68C04AE8  mov         ecx,dword ptr [eax+18h]  
 68C04AEB  mov         eax,dword ptr [ecx+60h]  
 68C04AEE  test        eax,eax  
 68C04AF0  je          DirectUI::XamlMobileDragOperation::EndOperation+86h (68C04B17h)  
 68C04AF2  and         dword ptr [ecx+60h],0  
 68C04AF6  test        eax,eax  
 68C04AF8  je          DirectUI::XamlMobileDragOperation::EndOperation+86h (68C04B17h)  
 68C04AFA  mov         ecx,dword ptr [eax]  
 68C04AFC  mov         edi,esp  
 68C04AFE  push        eax  
 68C04AFF  mov         esi,dword ptr [ecx+8]  
 68C04B02  mov         ecx,esi  
 68C04B04  call        dword ptr ds:[68F0D6ACh]  
 68C04B0A  call        esi  
 68C04B0C  cmp         edi,esp  
 68C04B0E  je          DirectUI::XamlMobileDragOperation::EndOperation+86h (68C04B17h)  
 68C04B10  mov         ecx,4  
 68C04B15  int         29h  
 68C04B17  mov         eax,dword ptr [this]  
 68C04B1A  mov         dword ptr [eax+54h],6  
 68C04B21  xor         eax,eax  
 68C04B23  jmp         DirectUI::XamlMobileDragOperation::EndOperation+9Dh (68C04B2Eh)  
 68C04B25  mov         ecx,esi  
 68C04B27  call        OnFailure<120> (68660254h)  
 68C04B2C  mov         eax,esi  
 68C04B2E  pop         edi  
 68C04B2F  pop         esi  
 68C04B30  pop         ebx  
 68C04B31  mov         esp,ebp  
 68C04B33  pop         ebp  
 68C04B34  ret         4

**Comment by oldnewthing** [comment] 2015-10-14 16:47
Yes, this is a known problem. The fix for this just missed build 10563. Look for it in 10564 or higher.

**Closed by oldnewthing** 2015-10-14 16:47 UTC

**Comment by csnazell** [comment] 2015-10-14 17:52
In which case, please mark up each sample with the build number required to run it on each platform.

Thanks.

**Comment by oldnewthing** [comment] 2015-10-14 18:25
We generally do if a build higher than 10240 is required. The problem is that the build number with the fix was not known until a few days ago.
