### ISSUE TITLE
Issue on Bluetooth Le Paired device on windows 10 1709

### ISSUE THREAD

**Issue by westside** [Microsoft/Windows-universal-samples#764] opened 2017-10-24 08:48 UTC
My App (http://bhaptics.com/download.html) had problem on Bluetooth Le connection after updating to windows 10 1709
So I tried sample app, and this sample is also not working. 

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BluetoothLE

The problem is that code below is successful only after pairing.
```
await _bluetoothLeDevice.GetGattServicesAsync(BluetoothCacheMode.Uncached); 
```

Is it a bug or did I miss something?

**Comment by westside** [comment] 2017-10-25 02:45
https://youtu.be/_wvd-S2UaRg 
This is a video i took
After pairing, connect is successful. 
However, after disconnected, I received unrechable everytime.

**Comment by oldnewthing** [comment] 2017-10-27 00:25
I've asked the Bluetooth team to investigate.

**Comment by nikname** [comment] 2017-11-08 11:55
Just for your information I'm dealing with the same issue

**Comment by behar21** [comment] 2017-11-25 21:20
ME TO

**Comment by oldnewthing** [comment] 2017-11-27 19:50
The Bluetooth team would like some more information to be able to diagnose the problem.  

To capture traces using the script:

* Unzip [bth_trace.zip](https://github.com/Microsoft/Windows-universal-samples/files/1507354/bth_trace.zip) to your computer. 
* Open an elevated (administrator) command prompt and perform the following actions in it.
* Run “ifr_setup_bth.cmd” to enable verbose tracing.
* Reboot or disable/enable the Bluetooth device in Device Manager, so that the verbose tracing takes effect.
* Run “bth_trace”, but do not press a key when prompted.
* Toggle the Bluetooth radio off-on via the quick action menu or force a power cycle of the remote device (we need the connection information).
* Repro the issue.
* Press any key in the logging command prompt to capture the log file. 

Create and attach a ZIP file with the following contents:

* `C:\bth_tracing.etl`
* `C:\windows\inf\setupapi.*.log`
* `C:\Windows\Panther\setupact.log`
* `C:\windows\logs\windowsupdate\*.*`
* Any relevant screen shots.

Include the exact OS build number and architecture (x86 or x64) that was being tested.

Thanks.

**Comment by nikname** [comment] 2017-11-28 09:27
Here is the [zip file](https://github.com/Microsoft/Windows-universal-samples/files/1509181/Issue.764.zip)

**Comment by oldnewthing** [comment] 2017-11-28 21:18
@nikname It looks like you forgot the `bth_tracing.etl` file. Can you upload that too? Thanks.

**Comment by nikname** [comment] 2017-11-29 08:18
I'm sorry. Here is the new [zip file](https://github.com/Microsoft/Windows-universal-samples/files/1512952/Issue.764.zip)

**Comment by westside** [comment] 2018-01-11 00:49
I think that this issue is fixed. 
Now my windows version is below
![image](https://user-images.githubusercontent.com/1837913/34803097-bcfe3ec6-f6b4-11e7-921e-b3ad9990ce99.png)

**Comment by JimmyHang** [comment] 2018-01-23 03:59
I'm running 16299.192 and it's not fixed on my system, i run the bluetooth troubleshooter, this fixed the radio status for a couple of mins, then it's gone, my keyboard and mouse can't be used right now..

**Comment by sandervs** [comment] 2018-02-19 13:45
Any update on this issue? 
When I run this example code and select the Custom Service that we use, I get a "Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll" error. The error code is "HRESULT: 0x80070020". Screenshot attached. Can anyone help me?
![afbeelding](https://user-images.githubusercontent.com/4950778/36380699-85dcfc3c-1583-11e8-8836-ed325a30cde7.png)

**Comment by oldnewthing** [comment] 2018-08-15 20:52
Feature team is unable to reproduce the problem in the latest Insider build.

**Closed by oldnewthing** 2018-08-15 20:52 UTC
Labels: mobile-connectivity, tracking
